/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/appointment`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-list`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-login`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-map`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/appointment`; params?: Router.UnknownInputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/feedback`; params?: Router.UnknownInputParams; } | { pathname: `/screens/hospitalList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/hospitalMap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/appointment`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/feedback`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-list`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-login`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-map`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital-register`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/appointment`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/feedback`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/hospitalList`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/hospitalMap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/appointment${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/feedback${`?${string}` | `#${string}` | ''}` | `/hospital-dashboard${`?${string}` | `#${string}` | ''}` | `/hospital-list${`?${string}` | `#${string}` | ''}` | `/hospital-login${`?${string}` | `#${string}` | ''}` | `/hospital-map${`?${string}` | `#${string}` | ''}` | `/hospital-register${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/appointment${`?${string}` | `#${string}` | ''}` | `/screens/dashboard${`?${string}` | `#${string}` | ''}` | `/screens/feedback${`?${string}` | `#${string}` | ''}` | `/screens/hospitalList${`?${string}` | `#${string}` | ''}` | `/screens/hospitalMap${`?${string}` | `#${string}` | ''}` | `/screens/login${`?${string}` | `#${string}` | ''}` | `/screens/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/appointment`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-list`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-login`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-map`; params?: Router.UnknownInputParams; } | { pathname: `/hospital-register`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/appointment`; params?: Router.UnknownInputParams; } | { pathname: `/screens/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/feedback`; params?: Router.UnknownInputParams; } | { pathname: `/screens/hospitalList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/hospitalMap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/register`; params?: Router.UnknownInputParams; };
    }
  }
}
